<a href="https://colab.research.google.com/github/juhee3199/Machine-learning_advanced-study/blob/master/basic/numpy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### numpy ndarray 개요

In [4]:
import numpy as np

array1 = np.array([1,2,3])
print(type(array1))
print(array1.shape)
print(array1.ndim)

<class 'numpy.ndarray'>
(3,)
1


In [6]:
list = [1,2,'test']  # int형이 모두 문자열로 변경됌.
array = np.array(list)
print(array, array.dtype)  # dtype : datatype

['1' '2' 'test'] <U21


In [8]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [9]:
### arange, zeros, ones

sequence_array = np.arange(10)
print(sequence_array)

print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [11]:
one_array = np.ones((3,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
### reshape

arr = np.arange(10)
print(arr)
arr1 = arr.reshape(2,5)
print(arr1)
arr2 = arr1.reshape(5,2)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
print(arr)
arr3 = arr.reshape(-1, 5)
print(arr3)
arr4 = arr.reshape(5,-1)
print(arr4)
arr5 = arr4.reshape(-1)
print(arr5)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


- np.reshape(-1, 1)

: 2차원, 1개의 컬럼을 가진 ndarray로 변경

In [29]:
arr1 = np.arange(8)
arr3d = arr1.reshape(2,2,2)
print(arr3d)

# 3차원 ndarry를 2차원으로 변경
arr5 = arr3d.reshape(-1,1)
print(arr5)
print()
# 1차원을 2차원으로 변경
arr6  = arr3d.reshape(-1,1)
print(arr6)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


- ndarry의 데이터셋 인덱싱

In [32]:
arr1 = np.arange(1, 10)
print(arr1)
print(arr1[2])

[1 2 3 4 5 6 7 8 9]
3


In [33]:
# 값 수정
arr1[0] = 9
arr1[-1] = 0
arr1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

In [34]:
arr2d = arr1.reshape(3,3)
print(arr2d)
arr2d[0,1]

[[9 2 3]
 [4 5 6]
 [7 8 0]]


2

In [36]:
# 슬라이싱

arr3 = arr1[0:3]
arr3 

array([9, 2, 3])

In [38]:
# 팬시 인덱싱

print(arr2d)
arr3 = arr2d[[0,1],2]  # row는 [0,1], col은 2
print(arr3)

[[9 2 3]
 [4 5 6]
 [7 8 0]]
[3 6]


In [51]:
print(arr2d[0, [0,2]])
print(arr2d[0, 0:3])  # 슬라이싱은 -1까지 적용되므로 0:3

[9 3]
[9 2 3]


In [56]:
# boolean indexing
print(arr1)
indexes = np.array([5,6,7,8])
arr4 = arr1[indexes]
print(arr4)

[9 2 3 4 5 6 7 8 0]
[6 7 8 0]


- 행렬의 정렬
  - np.sort() : 원 행렬 그대로 유지, 정렬된 행렬을 반환
  - ndarray.sort() : 원 행렬 자체를 변환, 반환 값은 None

In [67]:
# np.sort()

org_arr = np.array([3,1,9,5])
print(org_arr)
sort_arr1 = np.sort(org_arr)
print(sort_arr1)
print(org_arr)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]


In [68]:
# ndarry.sort()

sort_arr2 = org_arr.sort()
print(sort_arr2)
org_arr.sort()
print(org_arr)


None
[1 3 5 9]


In [71]:
desc = np.sort(org_arr)[::-1]
print(org_arr)
print(desc)

[1 3 5 9]
[9 5 3 1]


In [73]:
# 로우 방향으로 정렬
arr2d = np.array([[8,12],
                  [7,1]])
sort_arr2d_axis0 = np.sort(arr2d, axis=0)
print(sort_arr2d_axis0)

# 컬럼 방향으로 정렬
sort_arr2d_axis1 = np.sort(arr2d, axis=1)
print(sort_arr2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스 반환

In [75]:
org_arr = np.array([3,1,9,5])

sort_ind = np.argsort(org_arr)
print(sort_ind)


[1 0 3 2]


In [76]:
# 내림차순

sort_ind_desc = np.argsort(org_arr)[::-1]
sort_ind_desc

array([2, 3, 0, 1])

In [77]:
# 시험성적 순으로 학생이름 출력

name = np.array(['A', 'D', 'E','C', 'B'])
score = np.array([78, 95, 84, 98, 88])

sort_ind_asc = np.argsort(score)
print(sort_ind_asc)
print(name[sort_ind_asc])

[0 2 4 1 3]
['A' 'E' 'B' 'D' 'C']


- 선형대수 연산 : 행렬내적과 전치행렬 구하기

In [78]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])

np.dot(A,B)

array([[ 58,  64],
       [139, 154]])

In [79]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])